include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - "**/version.dart"
    - "bricks/**/__brick__"
    - "tool/**/__brick__"
