name: flakka_cli
description: A CLI for developing flakka projects
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  flakka_build: ^0.1.2-alpha.3
  flakka_build_runner: ^0.1.2-alpha.5
  mason: ^0.1.0-dev.53
  mason_logger: ^0.2.12
  meta: ^1.14.0
  package_config: ^2.1.0
  path: ^1.9.0
  pub_updater: ^0.4.0
#  result_monad:
  universal_io: ^2.2.2
dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.3
  test: ^1.25.4
  very_good_analysis: ^5.1.0
  very_good_cli: ^0.21.0


executables:
  flakka_cli:
