name: flakka_cli
description: A CLI for developing flakka projects
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  flakka_build:
    git: https://github.com/flakka-code/flakka_build
  flakka_build_runner:
    git: https://github.com/flakka-code/flakka_build_runner
  mason:
  mason_logger: ^0.2.12
  package_config:
  pub_updater: ^0.4.0
  result_monad:
dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.3
  test:
  very_good_analysis: ^5.1.0
  very_good_cli:

dependency_overrides:
  flakka_build:
    path: ../flakka_build
  flakka_build_runner:
    path: ../flakka_build_runner

executables:
  flakka_cli:
